/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.gov.utfpr.oop.exercicio19.produto;

/**
 *
 * @author pedro
 */
public class TelaProduto extends javax.swing.JFrame {

	/**
	 * Creates new form TelaProduto
	 */
	public TelaProduto() {
		initComponents();
		setVisible(true);
	}

	public void addListener(GerenciadorProduto g) {
		this.jbApagar.addActionListener(g);
		this.jbAtualizar.addActionListener(g);
		this.jbCadastrar.addActionListener(g);
		this.jbConsultar.addActionListener(g);
	}

	public Integer getCod() {
		return Integer.valueOf(this.jtfCod.getText());
	}

	public Produto getProduto() {
		Produto p = new Produto();

		p.setCod(Integer.valueOf(this.jtfCod.getText()));
		p.setDescricao(this.jtfDescricao.getText());
		p.setNome(this.jtfNome.getText());
		p.setPreco(Float.parseFloat(this.jtfPreco.getText()));
		return p;
	}

	public void setProduto(Produto p) {
		this.jtfCod.setText(p.getCod().toString());
		this.jtfDescricao.setText(p.getDescricao());
		this.jtfNome.setText(p.getNome());
		this.jtfPreco.setText(String.valueOf(p.getPreco()));
	}
	

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jlCod = new javax.swing.JLabel();
                jtfCod = new javax.swing.JTextField();
                jlNome = new javax.swing.JLabel();
                jtfNome = new javax.swing.JTextField();
                jlProduto = new javax.swing.JLabel();
                jtfDescricao = new javax.swing.JTextField();
                jlDescricao = new javax.swing.JLabel();
                jtfPreco = new javax.swing.JTextField();
                jlPreco = new javax.swing.JLabel();
                jbConsultar = new javax.swing.JButton();
                jbCadastrar = new javax.swing.JButton();
                jbApagar = new javax.swing.JButton();
                jbAtualizar = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jlCod.setText("cod:");

                jtfCod.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jtfCodActionPerformed(evt);
                        }
                });

                jlNome.setText("nome:");

                jtfNome.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jtfNomeActionPerformed(evt);
                        }
                });

                jlProduto.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
                jlProduto.setText("PRODUTO");

                jtfDescricao.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jtfDescricaoActionPerformed(evt);
                        }
                });

                jlDescricao.setText("descricao:");

                jtfPreco.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jtfPrecoActionPerformed(evt);
                        }
                });

                jlPreco.setText("preco:");

                jbConsultar.setText("consultar");
                jbConsultar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jbConsultarActionPerformed(evt);
                        }
                });

                jbCadastrar.setText("cadastrar");
                jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jbCadastrarActionPerformed(evt);
                        }
                });

                jbApagar.setText("apagar");
                jbApagar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jbApagarActionPerformed(evt);
                        }
                });

                jbAtualizar.setText("atualizar");
                jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jbAtualizarActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlProduto)
                                .addGap(151, 151, 151))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jlNome)
                                                                .addGap(28, 28, 28)
                                                                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jlCod)
                                                                .addGap(28, 28, 28)
                                                                .addComponent(jtfCod, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jlPreco)
                                                                        .addComponent(jlDescricao))
                                                                .addGap(28, 28, 28)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jtfDescricao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jtfPreco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(79, 79, 79)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jbConsultar)
                                                        .addComponent(jbAtualizar))
                                                .addGap(74, 74, 74)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jbApagar)
                                                        .addComponent(jbCadastrar))))
                                .addContainerGap(37, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlProduto)
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlCod)
                                        .addComponent(jtfCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlNome)
                                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlDescricao)
                                        .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlPreco)
                                        .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jbConsultar)
                                        .addComponent(jbCadastrar))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jbAtualizar)
                                        .addComponent(jbApagar))
                                .addContainerGap(22, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jtfCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jtfCodActionPerformed

        private void jtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jtfNomeActionPerformed

        private void jtfDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDescricaoActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jtfDescricaoActionPerformed

        private void jtfPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPrecoActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jtfPrecoActionPerformed

        private void jbConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jbConsultarActionPerformed

        private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jbCadastrarActionPerformed

        private void jbApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbApagarActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jbApagarActionPerformed

        private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jbAtualizarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaProduto().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jbApagar;
        private javax.swing.JButton jbAtualizar;
        private javax.swing.JButton jbCadastrar;
        private javax.swing.JButton jbConsultar;
        private javax.swing.JLabel jlCod;
        private javax.swing.JLabel jlDescricao;
        private javax.swing.JLabel jlNome;
        private javax.swing.JLabel jlPreco;
        private javax.swing.JLabel jlProduto;
        private javax.swing.JTextField jtfCod;
        private javax.swing.JTextField jtfDescricao;
        private javax.swing.JTextField jtfNome;
        private javax.swing.JTextField jtfPreco;
        // End of variables declaration//GEN-END:variables
}
